### ISSUE TITLE
Midi BGM not playing

### ISSUE THREAD

**Issue by kivutar** [libretro/easyrpg-libretro#1]
#### Name of the game:
TAUT
#### Player platform:
Windows, Linux, Android, ...
Linux
#### Attach files (as a .zip archive or link them)
I see a log message saying "Couldn't play BGM". They happen to be in MIDI format.
#### Describe the issue in detail and how to reproduce it:
Play the game until the bath scene.

**Comment by inactive123** [comment]
You need to put MIDI files inside the system directory.

'pats' is the directory they should go into.

This should be the freetimidity files. Inside that 'pats' directory should be another directory called 'Drum_000' and 'Tone_000'.

unfortunately I don't see a way yet to bake this in.

**Comment by kivutar** [comment]
Oh, MIDI files from the RTP I would understand, but the ones from the game itself? The wav files in the game folder are played correctly.

**Comment by Ghabry** [comment]
EasyRPG has a built-in MIDI synthesizer (FmMidi) btw. (compile with -DWANT_FMMIDI)
That thing is quite resource heavy because it doesn't use PAT/SF2 files but synthesizes the audio on the fly and works out of the box with 0 extra config files.
And the result sounds more "electronical" compared to PAT. (PAT comes quite close to what you would expect by Windows MIDI.)

Will be used as a fallback when WildMidi fails. (WildMidi always gets priority)
