### ISSUE TITLE
Upstream provides libretro build

### ISSUE THREAD

**Issue by guoyunhe** [libretro/easyrpg-libretro#47]
https://github.com/easyrpg/player#building-a-libretro-core

So should I use the upstream repo or this repo? What is the difference?

**Comment by Ghabry** [comment]
Purpose of this repo:
- Rate limiting. The libretro buildbot is slow and recompiles on push and this takes 12-24hours per push -> Prevent bot overload
- This disgusting stuff in builds/libretro/deps/libretro to get the dependencies built. Also kinda unsupported for custom setups. Imo this is bad style and I already had multiple discussions about this but the buildbot requires "baking in" of all the dependencies which means they are always extremely outdated and full of security issues.
- Everything else is upstream stuff. This repo is really just to work around infrastructure issues.

When you are able to install all the dependencies of EasyRPG Player (e.g. because they are managed by your distribution) it is highly recommended to use the upstream repo (e.g. the maintainer of the Kodi easyrpg-libretro core does this) at https://github.com/easyrpg/player and build through CMake as stated in the ReadMe.

Upstream fully supports targeting libretro.

**Comment by Ghabry** [comment]
Thanks for solving this :).

I consider this fixed.
