### ISSUE TITLE
Libretro core for windows (x86_64) is outdated (2019-11-12)

### ISSUE THREAD

**Issue by whocares0101** [libretro/easyrpg-libretro#50]
The nightly libretro core is quiet old, would it be possible to update this once in a while?

https://buildbot.libretro.com/nightly/windows/x86_64/latest/
easyrpg_libretro.dll
2019-11-12

**Comment by Ghabry** [comment]
Getting this to build on the buildbot is very frustrating and time consuming because easyrpg depends on many external libraries.

That's why I'm currently not motivated to fix this. Sorry.

**Comment by inactive123** [comment]
We have to move forward though in some way. So what are the options?

**Comment by Ghabry** [comment]
Do you offer something like docker or similar to replicate the buildbot? Imo the simplest solution is to precompile the dependencies outside of the core and then wget+link.

This is what we do upstream but it only works when you have full control over the environment,  that's why I asked about docker.

This will fail for unknown architectures but they can file bugs when this issue occurs.

For custom (Linux) builds I recommend using of system libraries. Lakka and opensuse already do this (which is great) so they are unaffected of this issue and are always up to date

**Comment by Kupo91** [comment]
Hi, will v0.6.3 released as libretro core again?

**Comment by Ghabry** [comment]
the latest is 0.6.2.2.
There will be builds when the gitlab migration is finished. (new buildbot)

**Comment by Ghabry** [comment]
no idea how the dependencies are collected but the core builds now for windows on the new buildbot

**Comment by whocares0101** [comment]
Great but I still don't see any easyrpg core here
https://buildbot.libretro.com/nightly/windows/x86_64/latest/
